- example_code/Makefile
This PR only adds the makefile for automating building and running the examples.  It's not perfect, but it should be a reasonable start for us to build on.
Note: the Fortran tests are not even compiling right now, so they are omitted from the ```run``` target.
Needs two reviews to merge: @dkhaldi @shamisp or others, please help
> Add Makefile for examples

- content/backmatter.tex
- content/shmem_wait.tex
- main_spec.tex
This PR adds generic interfaces for `shmem_wait` and `shmem_wait_until`.
This is Redmine ticket 216. This ticket had a formal reading at the August 2016 meeting, but this PR has a mostly-cosmetic cleanup in `shmem_wait` to condense redundant tables for C/C++ and Fortran. Merge is pending special ballot and formal ballot.
This ticket has a dependence on PR #6.
> Generic shmem_wait interfaces

- content/backmatter.tex
- content/shmem_lock.tex
- content/shmem_wait.tex
Ref: redmine ticket 211 (http://www.openshmem.org/redmine/issues/211)
> Remove volatile qualifiers in wait and lock API

- content/backmatter.tex
- content/environment_variables.tex
- content/shmem_malloc.tex
- content/shpalloc.tex
This PR renames SMA-prefixed environment variables to use the SHMEM prefix.
This is Redmine ticket 222. This ticket had a formal reading at the August 2016 meeting, but this PR includes subsequent changes to note the deprecated env-vars and update the deprecation and change-log annexes. Merge is pending special ballot and formal ballot.
> Rename SMA-prefixed env-vars to use SHMEM prefix

- content/backmatter.tex
- content/shmem_global_exit.tex
- utils/defs.tex
This PR adds the `_Noreturn` function specifier (C11) and `noreturn` attribute (C++11) to `shmem_global_exit`.
This is Redmine ticket 223. This ticket had a formal reading at the August 2016 meeting, but this PR includes subsequent changes to add C++11 support (as well as change highlighting). Merge is pending special ballot and formal ballot.
> Add _Noreturn specifier to shmem_global_exit

- content/library_constants.tex
List the constant once for all language bindings, instead of listing the
same thing twice for C/C++ and Fortran.
> Update SHMEM_SYNC_SIZE constant listing

- example_code/hello-openshmem.c
- example_code/shmem_add_example.c
- example_code/shmem_alltoall_example.c
- example_code/shmem_alltoalls_example.c
- example_code/shmem_barrier_example.c
- example_code/shmem_barrierall_example.c
- example_code/shmem_broadcast_example.c
- example_code/shmem_collect_example.c
- example_code/shmem_cswap_example.c
- example_code/shmem_fadd_example.c
- example_code/shmem_fence_example.c
- example_code/shmem_finc_example.c
- example_code/shmem_g_example.c
- example_code/shmem_global_exit_example.c
- example_code/shmem_inc_example.c
- example_code/shmem_iput_example.c
- example_code/shmem_lock_example.c
- example_code/shmem_mype_example.c
- example_code/shmem_npes_example.c
- example_code/shmem_p_example.c
- example_code/shmem_ptr_example.c
- example_code/shmem_put_example.c
- example_code/shmem_quiet_example.c
- example_code/shmem_swap_example.c
Bugs fixed:
- Add missing calls to `shmem_finalize()`
- Ensure tests exit with code 0 on success
- shmem_add_example.c: replace `shmem_add` with `shmem_fadd` (transcription error in preview version of the spec)
> Fix bugs in the C examples

- content/shmem_alltoall.tex
- content/shmem_alltoalls.tex
- utils/defs.tex
Buffer indexing in all-to-all collectives was incorrect for active sets
that contain a subset of PEs.
Ref: redmine ticket 208 (http://www.openshmem.org/redmine/issues/208).
> Correct active set indexing in a2a

- content/backmatter.tex
- utils/defs.tex
Redmine: http://openshmem.org/redmine/issues/202
The base commit for this pull request is essentially unchanged from #202 annexF_revision_proposal2.pdf (07/13/2016 01:11 PM) from the Redmine. Changes atop this base commit reflect feedback from the OpenSHMEM Workshop 2016 and misc additions.
- WORKSHOP: Simplified rationale text for **SHMEM_CACHE**
- NEW: Changed rationale text for **_SHMEM_\* constants**
- NEW: Table includes language specifiers for previously deprecated functions
- NEW: Changelog text (Where did v1.4 go?)
- Misc formatting
TODO: Table could still use some formatting wizardry. That's for another day.
> Extension #202: Improved Annex F for Deprecated API

- content/backmatter.tex
- content/language_bindings_and_conformance.tex
- content/shmem_info_get_name.tex
- content/shmem_info_get_version.tex
- utils/defs.tex
Added `\HEADER` command. Affects Annex A and API descriptions for `shmem_info_get_{version,name}`.
Also, there's a defs comment for \const{} vs. \CONST{}.
> DocEdit: Added \HEADER command

- content/backmatter.tex
At the specification meeting when #14, #15, and #16 were ratified, I took the action to clean up the verbiage for Annex G. This PR updates the change log for "1.5".
> Verbiage cleanup of Annex G ("Changes to this Document")

- content/backmatter.tex
Expands the SMA entry in the deprecation table and adds a deprecation rationale in the same style as the one for _my_pe and friends.
> Annex F: Expand SMA entry

- content/backmatter.tex
OpenSHMEM v1.2 deprecated these Fortran routines: START_PES, MY_PE, NUM_PES. These routines were missed when the Annex F table was labeled with `C/C++` and `Fortran` attributes in #25. The routines have been added back in as unique entries along with a rationale that seems appropriate until we officially deprecate the existing Fortran bindings.
Related to #33 in addendum to or as a potentially satisfactory resolution.
> Annex F: Add missing Fortran routines

- content/shmem_broadcast.tex
- content/shmem_collect.tex
- content/shmem_reductions.tex
The text describing Broadcast (and other collectives) operation in the current specification 
does not clarify the state of source buffer on root PE (read Page 51, 4-5), after it returns.
One would assume the source buffer is reusable.
> Fixing Source Buffer Ambiguity in Collective Operations Text (RM #217)

- content/backmatter.tex
- content/language_bindings_and_conformance.tex
Ref: [Redmine ticket 219](http://www.openshmem.org/redmine/issues/219)
> Clarify shmemx header is required, even when empty

- content/backmatter.tex
- content/shmem_calloc.tex
- main_spec.tex
This PR adds the `shmem_calloc` function.
**Special Ballot**: diff ([30e8392..d31f114](https://github.com/openshmem-org/specification/pull/47/files/30e83921293fc384ae2209bd99f775a5508e572f..d31f11466f364711add00743dc8843c065f07302)) and [PDF](https://github.com/openshmem-org/specification/files/838553/proposal-calloc-20170313.pdf)
Note that `shmem_calloc` was added separately from the `shmem_{malloc,realloc,align,free}` block because the argument descriptions would conflict.
> Add shmem_calloc function

- content/shmem_malloc.tex
This reverts commit fc2c0162cde0151cf6d4d2edac351f6a887ab950, reversing
changes made to 018862ff60b8c57ebddd6daa8d079419b06b5e26.
This change was incorrectly applied to master instead of osh_spec_next.  Reverting from master and re-applying to osh_spec_next.
> Revert "Merge pull request #38 from davidozog/pr/mem_manage_barriers"

- content/start_pes.tex
Inspired by #61, this PR adds deprecation markers to `start_pes()`. The rendered output is as follows:
> Add deprecation markers to start_pes()

- content/language_bindings_and_conformance.tex
- content/p2p_sync_intro.tex
- content/shmem_atomic_add.tex
- content/shmem_atomic_compare_swap.tex
- content/shmem_atomic_fetch.tex
- content/shmem_atomic_fetch_add.tex
- content/shmem_atomic_fetch_inc.tex
- content/shmem_atomic_inc.tex
- content/shmem_atomic_set.tex
- content/shmem_atomic_swap.tex
- content/shmem_malloc.tex
* Fix verb tense in atomics text
* Update plural acronyms to use \acp{} macro
> Housekeeping

- content/backmatter.tex
- content/library_constants.tex
`SHMEM_MAX_NAME_LEN` now represents the maximum string length instead of the actual string length. The original definition has ambiguous implications with whether null/blank characters at the end of the relevant characters were counted or not.
Potentially a DocEdit, but this change technically relaxes the existing semantics even if the original semantics were sometimes not used in practice.
> Relaxed definition of SHMEM_MAX_NAME_LEN

- content/backmatter.tex
Essentially deprecated since OpenSHMEM 1.0, but OpenSHMEM 1.0 did not
*technically* list the mpp directory in Appendix A (Deprecated Items),
but rather as a Compatibility Note. This note disappeared in OpenSHMEM
1.1 and is now being restored for completeness.
Deprecation is assumed to have occured in OpenSHMEM 1.1.
> Deprecated header directory mpp

- content/backmatter.tex
As of these edits, all instances of 'we', with one exception, have been removed from the document. The exception is located in the acknowledgements section on page iii and was left untouched because usage of pronouns is appropriate in this section of the document.
> Removing 'we' from spec.

- content/shmem_alltoall.tex
- content/shmem_alltoalls.tex
- content/shmem_atomic_add.tex
- content/shmem_atomic_compare_swap.tex
- content/shmem_atomic_fetch_add.tex
- content/shmem_atomic_fetch_inc.tex
- content/shmem_atomic_inc.tex
- content/shmem_atomic_swap.tex
- content/shmem_barrier.tex
- content/shmem_broadcast.tex
- content/shmem_cache.tex
- content/shmem_collect.tex
- content/shmem_get.tex
- content/shmem_get_nbi.tex
- content/shmem_iget.tex
- content/shmem_iput.tex
- content/shmem_lock.tex
- content/shmem_ptr.tex
- content/shmem_put.tex
- content/shmem_put_nbi.tex
- content/shmem_quiet.tex
- content/shmem_reductions.tex
- content/shmem_wait.tex
- content/shpalloc.tex
Removed use of 'you' from document and replaced with impersonal expressions.
Signed-off-by: Michael Culhane <j.mike.culhane@gmail.com>
> Removing 'you' from Spec

- content/atomics_intro.tex
- content/backmatter.tex
- content/library_constants.tex
- content/p2p_sync_intro.tex
- content/programming_model_overview.tex
- content/rma_intro.tex
- content/shmem_alltoalls.tex
- content/shmem_barrier_all.tex
- content/shmem_collect.tex
- content/shmem_iget.tex
- content/shmem_info_get_name.tex
- content/shmem_info_get_version.tex
- content/shmem_iput.tex
- content/shmem_malloc.tex
- content/shmem_ptr.tex
- content/shmem_reductions.tex
- content/shpalloc.tex
- main_spec.tex
- utils/defs.tex
Currently, this PR includes:
* `\ac{API}s` -> `\acp{API}`
* `\Fortran{}` -> `\Fortran`
* `\openshmem{}` -> `\openshmem`
* `\textit{...}` -> appropriate macro
* Manual fixes for TOC generation (see f9e1887 for details)
This PR would close #66.
> General LaTeX doc-edit cleanups

- content/collective_intro.tex
- content/shmem_alltoall.tex
- content/shmem_alltoalls.tex
- content/shmem_barrier.tex
- content/shmem_broadcast.tex
- content/shmem_collect.tex
- content/shmem_reductions.tex
- content/synchronization_model.tex
- utils/defs.tex
The purpose of this file is to change the formatting of the term ‘active set,’ **and one instance of the term ‘collective routines,’** so that they are consistent with the way other important terms appear in the spec. The following is an explanation justifying the edit:
When an important term is introduced in the spec it is written in italics and every first letter is capitalized. Symmetric data objects, for example, reads as _Symmetric Data Objects_ when first introduced. Every subsequent time an important term appears, all letters are written in the lower case and the term is not italicized. The term ‘active set,’ when it first appears, reads like so: _Active set_. Collective routines, when it first appears, also follows this formatting. Almost every subsequent time ‘active set’ appears …
> Consistency edits for the term: active set.

- content/backmatter.tex
- content/shmem_barrier_all.tex
- content/shmem_finalize.tex
- content/shmem_init_thread.tex
- content/shmem_query_thread.tex
- content/shmem_quiet.tex
- content/shmem_wait.tex
- content/synchronization_model.tex
- content/threads_intro.tex
- main_spec.tex
This proposal specifies the interaction between OpenSHMEM interfaces and the user threads. 
Further, also introduces interfaces to initialize and query thread-safe OpenSHMEM library.
> Thread Safety Proposal (RM Ticket #218)

- utils/packages.tex
Some of these tables are getting pretty big. I need a way to break them across pages without jumping through hoops. This addition affects multiple sections, with intent for tables in: 6 Library Constants, C Undefined Behavior, and F Deprecation.
> Add `longtable` to packages

- content/p2p_sync_intro.tex
- content/shmem_wait.tex
In Issue #84, @jamesaross raised the concern / made the observation that, as written, #32 both deprecated the `shmem_wait` and `shmem_TYPE_wait` routines and expanded the required type support of the API. This PR revises the changes in #32 to deprecate `shmem_wait` _without_ expanding the type support.
> Remove expanded type support for the newly-deprecated shmem_wait

- example_code/shmem_test_example1.c
PR #32 was ratified with the expectation that the `shmem_test()` example would be updated to a runnable example and not merely be a function demonstrating the use of `shmem_test()` (see Issue #68). This PR should close out #68.
Here's looking at you, @shamisp.
> Update shmem_test() example to be runnable

- example_code/shmem_ctx_pipelined_reduce.c
Fix a couple "shmemx" function name typos.  These are left over from when I ran this example on the SOS prototype implementation of contexts, which used the "shmemx_" prefix instead of "shmem_" for the new routines.
> Fix typo in function name

- content/shmem_calloc.tex
- content/shmem_malloc.tex
In symmetric heap management routines, clarify requirements on size and alignment arguments and resulting behavior.
* a `size` of zero results in no action and returns a null pointer
* `alignment` must be a power-of-two multiple of `sizeof(void*)` or behavior is undefined
* symmetric heap management routines that perform no action also perform no barriers
Closes #76 
Closes #78
> Symmetric Heap: Clarify size and alignment semantics

- content/collective_intro.tex
* Clarify that the active set does not "wrap around" (starting PE is lowest numbered PE)
* Clarify that `logPE_stride` must be greater that or equal to zero
* Clarify that `PE_size` must be greater than zero
* Clarify that last member must correspond to a valid PE number
* Clarify that if any of the above are not met, behavior is undefined
Closes #197
> Clarify PE active set requirements

- content/backmatter.tex
This PR adds the basic framing for the OpenSHMEM 1.5 changelog.  I'd like to add this as a document edit to avoid the same changes being replicated across multiple PRs.
> Add template for OpenSHMEM 1.5 changelog

- content/rma_intro.tex
- content/shmem_broadcast.tex
- content/shmem_wait_until.tex
This is a mixed bag of clarifying edits that were pointed out by a colleague reading the OpenSHMEM specification for the first time.  These edits are intended to improve the clarity/readability of the document without changing any semantics.
> Mixed bag of clarifying edits

- content/backmatter.tex
- content/memory_model.tex
- content/p2p_sync_intro.tex
- example_code/amo_scenario_1.c
- example_code/amo_scenario_2.c
- example_code/amo_scenario_3.c
- utils/defs.tex
Clarify the various cases that violate atomicity.  There should be no semantic changes.
Closes #172
> Update atomic memory model text

- content/backmatter.tex
- content/shmem_lock.tex
- example_code/shmem_lock_example.c
* Reorganize text to describe lock API before unlock API
* Define unlock as performing quiet; this clarifies the interaction with contexts and nonblocking API routines
* Define OpenSHMEM locks to be non-reentrant; this clarifies the  behavior when used by multithreaded PEs
Closes #205
Closes #193 
Closes #174
> Clarify semantics of lock API

- content/backmatter.tex
Annex D is slowly bit rotting and contains information that is duplicated from elsewhere in the spec. 
Per discussion on #191, the proposed solution is to remove this annex.
Closes #191
> Remove interoperability annex

- content/backmatter.tex
- utils/defs.tex
Removing unnecessary white spaces in the backmatter and def files.
> DOC-edit: RM unnecessary white spaces in backmatter and defs

- content/backmatter.tex
We broke the following reference in the OpenSHMEM 1.1 changelog with #215:
```
LaTeX Warning: Reference `sec:mpi' on page 126 undefined on input line 836.
```
> Fix broken reference

- content/backmatter.tex
I forgot to add a change-log entry in PR #274, so this PR takes care of that.
I also reworded the any/all/some bullet to be more consistent with the other change-log entries.
> Add change-log entry for the wait/test "vector" API

- content/shmem_malloc_hints.tex
- main_spec.tex
Proposal to address the issue https://github.com/openshmem-org/specification/issues/258 .
> Adding shmem_malloc_with_hints interface

- .github/workflows/main.yml
This PR sets up a [GitHub Actions](https://help.github.com/en/actions) workflow to generate a draft OpenSHMEM PDF and upload the PDF as a build artifact. This will make the generated PDFs available on every PR/push.
In the eventual v2 release of [actions/upload-artifact](https://github.com/actions/upload-artifact), this workflow could be modified to upload the PDF artifact directly (vs. zipped; see https://github.com/actions/upload-artifact/issues/3) and possibly use the short (vs. full) commit hash.
@jdinan Please 'Squash and Merge' when ready/approved.
> Create GitHub Action workflow

- content/shmem_collect.tex
- content/shmem_ctx_create.tex
- content/shmem_sync.tex
- content/shmem_team_create_ctx.tex
- content/teams_intro.tex
- example_code/shmem_sync_example.c
- example_code/shmem_team_context.c
Edits captured on #282 moved here for section committee review
> Teams edits from September F2F

- content/backmatter.tex
- content/library_constants.tex
- content/shmem_malloc_hints.tex
As per discussion during the Nov spec meeting, the names of the HINTS are changed as below:
**SHMEM_HINTS_ATOMICS_REMOTE -> SHMEM_MALLOC_ATOMICS_REMOTE**
**SHMEM_HINTS_SIGNAL -> SHMEM_MALLOC_SIGNAL_REMOTE**
> Change HINTS name for SHMEM_MALLOC_WITH_HINTS interface

- content/shmem_reductions.tex
The current text has been around since at least as far back as the T3E documentation, but it's hard (at least for me) to grok.  This PR updates the description of src/dest overlap using the language from the original SHMEM collectives document, ["SHMEM User’s Guide for C" by Barriuso and Knies '94](https://www.cs.cmu.edu/afs/cs/project/cmcl/link.iwarp/OldFiles/archive/fx-papers/cri-shmem-users-guide.ps).
> Clarify reduction src/dest overlap text

- .github/workflows/main.yml
The initial GitHub action would run on a push for a branch or active PR, but not on the initial PR. I think this fixes that.
> Run GitHub workflow on PR

- content/backmatter.tex
- content/shmem_barrier.tex
- content/shmem_malloc_hints.tex
- content/shmem_n_pes.tex
- content/shmem_ptr.tex
Document edit (whitespace only) to remove hard tabs and generally fix indentation. Needs two reviews to be merged as a document edit.
@manjugv This touches a couple of your edits, would appreciate if you can review.
> Remove hard tabs

- content/shmem_signal_wait_until.tex
We were addressing the partial update completions in the apinotes
for the shmem_wait_until_signal op. To be consistent with other
sync operations - moving to the description section.
Addresses issue #357
> Update full/partial completion to signal_wait_until

- content/backmatter.tex
- content/frontmatter.tex
- utils/defs.tex
This PR removes the line numbering on the pages of the Specification. These numbers are not referenced in the document itself, nor do they actually align with the lines of text. They cause copy-paste errors for examples (see https://github.com/openshmem-org/specification/pull/237#issuecomment-582513835).
> Remove line numbers from the PDF

- content/library_handles.tex
This ticket reverts the proposed change from #307 (to relax the correspondence of `SHMEM_TEAM_SHARED` with `shmem_ptr`) and instead specifies that _all_ symmetric heap objects on the PEs must be accessible for those PEs to be included in `SHMEM_TEAM_SHARED`.
Some more background information:  We learned from #307 that we generally prefer `SHMEM_TEAM_SHARED` and `shmem_ptr` to have a direct correspondence.  We also realized that the `shmem_ptr` interface allows implementations to freely limit accessibility, which resolves any problems with representing non-triplet teams (thanks @minsii!).  We also became aware that `shmem_ptr` may lack "symmetry" with regard to other PE's, and may lack "coverage" with regard to the whole symmetric heap/data segments ([discussed …
> Clarify SHMEM_TEAM_SHARED membership via shmem_ptr

- content/atomics_intro.tex
- content/shmem_reductions.tex
- main_spec.tex
- utils/defs.tex
* Adding macro for subsubsubsection
* Moving blocking and non_blocking RMA into one subsubsection
* Moving blocking and non_blocking AMO into one subsubsection
* Updating AMO introduction to reflect support for non_blocking
operations
* Reduction paragraph was replaced with subsubsubsection to make the
text consistent
Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>
> RMA, AMO, Reduction edits

- content/backmatter.tex
Simple backmatter fix for my bad typo in the *History of OpenSHMEM* annex.
> Fix typo in History: SGI -> Cray

- content/synchronization_model.tex
Reduced the size of the figures for barrierall and sync - the size
is similar to all other figures and it fits well within the page
limit.
This is better than recreating the images and making some extensive changes.
Hope this is fine.
> Reduce barriall and sync figure alignements

- content/backmatter.tex
- content/coverpage.tex
- content/interoperability.tex
- content/library_constants.tex
- content/memory_model.tex
- content/profiling_interface.tex
- content/shmem_reductions.tex
- content/the_openshmem_effort.tex
Use `\ac{}` with instances of RMA, AMO, API.
There's one exceptional case on the cover page where I used the short-form `\acs` to preserve rendering as "RMA, AMO, and Signals Committee Chair".
> Acroynm-ize `RMA`, `AMO`, `API`

- main_spec.tex
cc https://github.com/openshmem-org/specification/pull/423
I forgot to grep `main_spec.tex` so here are those changes.
> Acronym-ize `API` and `AMO` in main_spec

- content/backmatter.tex
Closes https://github.com/openshmem-org/specification/issues/429
Makes the PDF bookmark easier to glance toward.
> Shorten annex heading for Deprecated API

- content/backmatter.tex
This PR clarifies the undefined-behavior "Concurrent use of teams" entry that was a discussion point on the April 27, 2020 v1.5rc2 meeting.
- Changed focus of first sentence to warn that team-based collectives
are not thread-safe if operating on the same team object. All team-based
collectives take a `\VAR{team}` argument input.
- Amended second sentence to now say "may be undefined behavior".
This precludes concurrent thread-safe usage of a team in operations such
as `shmem_team_translate_pe`.
- Explicitly emphasized the example as concurrent collective on the same
team object, `SHMEM_TEAM_WORLD`. This leads the application developer
toward a viable solution for this usage: clone the world team (though it
does beg the question of whether implementers could also clone
the world team to …
> Clarify undefined-behavior entry for concurrent use of teams

- content/coverpage.tex
We reviewed the proposed copyright and license updates at the April 27 RCM and concluded that more time is needed to adopt these changes. In the meantime, we felt it would be appropriate to adopt this permission to copy statement that is used by MPI.
> Add permission to copy statement

- content/programming_model_overview.tex
Updating the programming model overview section in the introduction
segment with the team and put-with-signal information
Closes #430
> Update pmodel overview with team and pws info

- content/memory_model.tex
Remove "for example" that has caused some confusion in AMO section. The examples following this paragraph more directly and clearly address the specific requirements for atomicity.
Closes #395
> Remove confusing "for example" from AMO description

- .github/workflows/main.yml
PR #449 has an error in the GitHub CI:
```
E: Unable to locate package texlive-generic-recommended
```
Looks like it's due to the `ubuntu-latest` image now being 20.04 (Focal), where this package is no longer available.
This fix one option: to ignore missing packages in `apt-get update`.  Another option is to remove this package entirely, which I tested and seems to build the spec successfully.  Any preference?
> Ignore missing packages in Github CI workflow

- content/shmem_test_all.tex
- content/shmem_test_all_vector.tex
Fixes inconsistency in return value for `shmem_test_all{_vector}`
Closes #442
> Fix inconsistency in return value for shmem_test_all{_vector}

- example_code/shmem_team_split_2D.c
The Clang compiler (at least) warns about not initializing the x, y, and z dimensional variables in the `shmem_team_split_2D.c` example code.
This is pretty low priority because the `find_xyz_dims` function should successfully set these variables (unless `shmem_n_pes` or `cbrt(npes)` return something unexpected) but we should fix it anyway.  An error check on these variables after `find_xyz_dims` is an alternative approach.
> Resolve compiler warning in 2D team split example

- content/backmatter.tex
- content/shmem_reductions.tex
* Delete incorrect type table
* Move correct team/active set type tables to the top of the reductions section
* Add missing type table references for team-based C APIs
Closes #460
> Fix type table issue in reductions section

- content/backmatter.tex
- content/shmem_team_split_2d.tex
- content/shmem_team_split_strided.tex
- example_code/shmem_team_split_2D.c
This PR is meant to address #450 (as well as https://github.com/Sandia-OpenSHMEM/SOS/issues/969 and https://github.com/Sandia-OpenSHMEM/SOS/issues/972).
I don't believe https://github.com/openshmem-org/specification/commit/8b44a29f6075a666aa3fcb3a9d123d1e808c0ec8 is a semantic change - just a clarification that a split operation on a SHMEM_TEAM_INVALID parent is indeed considered "unsuccessful" and the routine should return a nonzero value.
I also included a small change to the 2D team split example code (https://github.com/openshmem-org/specification/commit/ec66ff256fe78c9dba04afdb90b23bd02e66f22b).  This has no effect on the example, but leaving these variables uninitialized commonly causes a compiler warning.  Please let me know if you prefer this in a separate PR...
> Clarify return value for team split on SHMEM_TEAM_INVALID

- content/backmatter.tex
- content/memmgmt_intro.tex
- content/memory_model.tex
- content/shmem_align.tex
- content/shmem_free.tex
- content/shmem_malloc.tex
- content/shmem_realloc.tex
- main_spec.tex
This PR moves the combined entries of `shmem_{malloc, free, align, realloc}` into separate API entries for each. It also expands on the memory management introduction with text common across all four routines.
No semantic changes are intended. The git diff may not be very helpful. Comparing PDFs is probably the best approach.
Closes #212
> Split memory management routines into separate entries

- content/backmatter.tex
- content/shmem_pe_quiet.tex
- main_spec.tex
> Per PE Quiet interface

- content/backmatter.tex
- content/shmem_fence.tex
Clarify that Fence operations only guarantee ordering for operations that are performed on the same context.
> Clarify fence orders only within same context

- content/shmem_reductions.tex
In OpenSHMEM 1.4, we required that the `source` and `dest` pointers correspond to the same symmetric object:
> The same dest and source arrays, and the same pWrk and pSync work arrays, must be passed to all PEs in the active set.
However, we lost this text in OpenSHMEM 1.5. This PR adds it back.
> In reductions, src and dest must be same at all PEs

- content/backmatter.tex
- content/shmem_signal_add.tex
- content/shmem_signal_set.tex
- main_spec.tex
- Adds `shmem_signal_{add,set}`
- Revises the signaling operations introduction and atomicity sections accordingly
Closes #382
> Add shmem_signal_{add,set}

- content/backmatter.tex
- content/shmem_ibget.tex
- content/shmem_ibput.tex
- content/shmem_iget.tex
- content/shmem_iput.tex
- main_spec.tex
Extend the SHMEM strided APIs (e.g. `shmem_iput`) to include a block size, e.g.:
```
void shmem_ibput(TYPE *dest, const TYPE *source, ptrdiff_t dst, ptrdiff_t sst,
size_t bsize, size_t nblocks, int pe);
```
See #365 for details.
> Add Block-Strided RMA Operations

- content/backmatter.tex
- content/execution_model.tex
- content/shmem_finalize.tex
- content/shmem_init.tex
- content/shmem_init_thread.tex
- content/shmem_query_initialized.tex
- content/shmem_query_thread.tex
- main_spec.tex
> Add Multi-init/finalize Support

- content/collective_intro.tex
- content/memmgmt_intro.tex
- content/teams_intro.tex
This is a short list of typos (and a helpful hyphen) throughout the spec.
> Suggested v1.6 doc-edits throughout the spec

- content/shmem_malloc_hints.tex
Remove `/newline` in `shmem_malloc_hints` table. Prevents compilation in TeX Live 2023 and 2024.
> Remove /newline shmem_malloc_hints table, prevents compilation

- content/backmatter.tex
- content/shmem_align.tex
- content/shmem_free.tex
- content/shmem_malloc.tex
- content/shmem_malloc_hints.tex
- content/shmem_realloc.tex
This clarifies that all memory management routines are collective on the world team.
These changes may not be strictly necessary (it seems to be covered in the `Memory Management Routines` intro), but might provide some explicit clarity for new users.
> Clarify memory managment routines are world-collective

- content/backmatter.tex
- content/shmem_team_split_strided.tex
This addresses #491 by clarifying the behavior of team split operations when `stride` is zero or negative.
> Teams: clarify behavior of split ops with strides <= 0

- content/backmatter.tex
- content/shmem_team_get_config.tex
This attempts to clarify the behavior of `shmem_team_get_config` when `config_mask` is 0 and/or `config` is a null pointer.  It relates to issue #447.
> team_get_config: clarify config_mask == 0 and config == NULL cases

- content/backmatter.tex
- content/shmem_team_get_config.tex
This PR attempts to address #374.
I'm a bit unsure this expresses the desired behavior... I'm at least hoping to start discussing how best to clarify this.
> team_get_config: return the *current* config values

- content/shmem_scan.tex
- example_code/shmem_scan_example.c
- main_spec.tex
This PR adds inclusive and exclusive scan (prefix sum) operations as `shmem_sum_inscan` and `shmem_sum_exscan` operations. Some comments:
- MPI's inclusive scan is just called `MPI_Scan`.
- `MPI_Exscan` leaves the contents of the destination buffer on rank 0 undefined. The proposed `shmem_sum_exscan` explicitly zeros the destination buffer on PE 0. (Rationale: `MPI_Exscan` supports multiple operators; this PR only supports addition.)
- C++ uses the "full" names: [std::inclusive_scan](https://en.cppreference.com/w/cpp/algorithm/inclusive_scan), [std::exclusive_scan](https://en.cppreference.com/w/cpp/algorithm/exclusive_scan)
- Inclusive scan [seems somewhat more common](https://en.wikipedia.org/wiki/Prefix_sum#Inclusive_and_exclusive_scans), though I personally envision using exclusive …
> Add inclusive and exclusive scan (prefix sum) operations

- content/backmatter.tex
- content/interoperability.tex
https://github.com/kwaters4/specification/pull/7 changelog: entry for src buffer reqs in collectives
https://github.com/kwaters4/specification/pull/6 backmatter: add changelog for no team wrap-arounds
https://github.com/kwaters4/specification/pull/5 [ChangeLog] Add inclusive and exlcusive scan
https://github.com/kwaters4/specification/pull/4 [Appendix D 1.4] Add shmem_my_pe as a standard way to get process ID
https://github.com/kwaters4/specification/pull/3 [Annex C] Remove trapped and replace with detect
https://github.com/kwaters4/specification/pull/2 Add an "Errata" section
https://github.com/kwaters4/specification/pull/8  [reduction associativity] (changelog: entry for associativity of reductions)
> [SHMEM 1.6 Backmatter] Backmatter section committee changes

- content/profiling_interface.tex
- content/shmem_pcontrol.tex
Includes minor grammatical changes and whitespace fixes.
> [SHMEM 1.6 Section 10] Profiler Section Committee Changes

- content/shmem_test_all_vector.tex
Fix duplicate text in the description for shmem_test_all_vector
In the API description for shmem_test_all_vector there is duplicate text that says when nelems is 0 the function returns 1.
> [SHMEM 1.6 Sec. 9.11] Sychronization

- content/shmem_calloc.tex
- content/shmem_finalize.tex
- content/shmem_global_exit.tex
- content/shmem_init.tex
- content/shmem_malloc.tex
- content/shmem_malloc_hints.tex
- content/shmem_ptr.tex
- content/shmem_query_initialized.tex
- content/shmem_team_ptr.tex
- content/threads_intro.tex
- main_spec.tex
This PR includes text updates, clarifications, and changes related to the recent additions to the OpenSHMEM spec. Some of the key changes are - 
1. Deprecated block for `start_pes`
2. Clarifications on when `query_initialized` can be called and moved it to Section 9.1
3. Reorganizing texts between `malloc` and `malloc_hints`
4. Text edits, typo fixes
> [SHMEM 1.6 Sec 9.1 - 9.3] Clarifications and updates to setup, thread, and memory 

- content/coverpage.tex
- content/library_constants.tex
- content/memory_model.tex
- content/programming_model_overview.tex
- example_code/amo_scenario_3.c
- utils/defs.tex
This adds new 1.6 features to the front matter overview list and constant table and cleans up a few other areas. Specifically this:
- Adds new routines to the overview list and constant table for sessions, new signaling operations, and scan
- Updates the collectives overview to avoid talking about active-set specific behavior
- Tries to make the atomic overview language more consistent and adds missing routines
- Specifies that allocation routines are collective to match changes in the memory management section
- Removes deprecated functions from amo example 3 (`sum_to_all` -> `reduce`)
- Adds initial list of 1.6 contributors
> [SHMEM 1.6 Sec 1-8] Updates and additions to front matter 

- content/shmem_team_split_strided.tex
- example_code/shmem_ctx.c
This PR updates the teams and context section for 1.6. It includes:
[wokuno#1](https://github.com/wokuno/specification/pull/1): Fix shmem_team_split_strided's start argument wording
[wokuno#2](https://github.com/wokuno/specification/pull/2): teams: split does not permit parent PE wrap-around
[wokuno#3](https://github.com/wokuno/specification/pull/3): Updated example 14 for OpenSHMEM 1.5
[kwaters4#6](https://github.com/kwaters4/specification/pull/6) backmatter: add changelog for no team wrap-arounds
> [SHMEM 1.6 Sec 9.4-9.5] Updates to Teams and Context

- content/atomics_intro.tex
- content/backmatter.tex
- content/execution_model.tex
- content/frontmatter.tex
- content/memmgmt_intro.tex
- content/rma_intro.tex
- content/shmem_addr_accessible.tex
- content/shmem_alltoalls.tex
- content/shmem_barrier_all.tex
- content/shmem_broadcast.tex
- content/shmem_collect.tex
- content/shmem_finalize.tex
- content/shmem_g.tex
- content/shmem_init_thread.tex
- content/shmem_malloc_hints.tex
- content/shmem_p.tex
- content/shmem_pe_quiet.tex
- content/shmem_ptr.tex
- content/shmem_reductions.tex
- content/shmem_scan.tex
- content/shmem_team_ptr.tex
- content/shmem_wait_until_all.tex
- content/shmem_wait_until_all_vector.tex
- content/shmem_wait_until_any.tex
- content/shmem_wait_until_any_vector.tex
- content/shmem_wait_until_some.tex
- content/shmem_wait_until_some_vector.tex
- content/the_openshmem_effort.tex
> Remove unnecessary whitespace

- content/shmem_test_all_vector.tex
- content/shmem_test_any_vector.tex
- content/shmem_test_some_vector.tex
- content/shmem_wait_until_all_vector.tex
- content/shmem_wait_until_any_vector.tex
- content/shmem_wait_until_some_vector.tex
Add const to *cmp_values in vector synchronization apis
> Add const to cmp_value parameters of vector synchronization apis

- content/shmem_team_ptr.tex
- content/threads_intro.tex
This PR addresses #541 and also clarifies that `shmem_team_ptr` behavior is same as `shmem_ptr` when the team argument equals `SHMEM_TEAM_WORLD`.
> [SHMEM 1.6rc2 Sec 9.1-9.3] Clarification of team_ptr with TEAM_WORLD and multi-init with different thread levels 

- content/collective_intro.tex
- content/shmem_alltoall.tex
- content/shmem_broadcast.tex
- content/shmem_collect.tex
- content/shmem_reductions.tex
- content/shmem_scan.tex
This PR is a placeholder for any changes from the Collectives section subcommittee for v1.6 RC2.
It ~~currently only~~ adds a whitespace fix.
It ~~will likely~~ includes the following doc-edit adding scan to the list of team-based collectives:
https://github.com/davidozog/openshmem-specification/pull/15
And ~~_possibly_~~ a note about reduction associativity/commutativity:
https://github.com/davidozog/openshmem-specification/pull/16
And ~~possibly~~ a wording change for clarity:
https://github.com/davidozog/openshmem-specification/pull/13
~~Now just waiting on reviews for those last 2 PRs @kwaters4 @isubsmith @BKP @maawad~~
> Collectives Section Committee RC2 changes

- content/shmem_team_split_strided.tex
Clarify the example language for `shmem_team_split_strided` wrap-around
[wokuno#4](https://github.com/wokuno/specification/pull/4)
> Teams and Context Section Committee RC2 changes

- content/coverpage.tex
- content/library_handles.tex
- content/programming_model_overview.tex
Add new contributors to RC2, add `shmem_team_ptr` to existing `shmem_ptr` wording in the definition of `SHMEM_TEAM_SHARED`, and add a definition of "remote PE"
> Frontmatter Section Committee RC2 changes

- content/backmatter.tex
This demarcates the change in https://github.com/openshmem-org/specification/pull/543 is an erratum for OpenSHMEM v1.5.
It is meant to resolve https://github.com/orgs/openshmem-org/projects/5/views/1?pane=issue&itemId=82963558
> [SHMEM 1.6rc2 Backmatter] Errata Changes

- content/backmatter.tex
This addresses issue https://github.com/openshmem-org/specification/issues/555 by adding the new (as of v1.6) undefined behaviors regarding team splits to Annex C.  The text should be verbatim relative to the API description content.
@ahayashi @kwaters4
> Add v1.6 team split undefined behaviors to Annex C
