openshmem-org/specification

- .travis.yml
- makefile
Travis will automatically build pull requests and verify that the changes compile.
> Add Travis CI testing

- content/backmatter.tex
- content/library_constants.tex
This proposal was ratified at the August meeting and is ready to be merged.
> Add SHMEM_SYNC_SIZE constant

- content/backmatter.tex
- content/shmem_barrier.tex
- content/shmem_barrier_all.tex
- content/shmem_fence.tex
- content/shmem_quiet.tex
- content/shmem_wait.tex
Redmine issue http://www.openshmem.org/redmine/issues/169
> Semantics clarification for visibility ordering guarantees.

- content/backmatter.tex
- utils/defs.tex
Update the specification version at the request of the OpenSHMEM committee chair.
This PR is a "document edit" and is intended to be merged with the full reading/voting process.  However, we do need +2 to merge, so please review if you have time.
> Update spec version to 1.4

- content/coverpage.tex
I would like to propose that we add a dedication to OpenSHMEM 1.4 to honor David.
> Add dedication to David Knaak in OpenSHMEM 1.4

- content/shmem_cache.tex
Add deprecation begin/end markers around cache API description.
> Add deprecation markers to cache API

- content/shmem_collect.tex
- content/shmem_fence.tex
- content/shmem_reductions.tex
- content/start_pes.tex
Very minor latex fixes.  
I could submit this PR to @nspark's [docedit/general-cleanup](https://github.com/nspark/specification/tree/docedit/general-cleanup) branch if we prefer fewer PRs for this sort of stuff...
> Some minor latex fixes

- content/library_constants.tex
- content/library_handles.tex
- utils/defs.tex
> Mark Fortran constants as deprecated

- content/backmatter.tex
- content/shmem_malloc.tex
- content/shpalloc.tex
- utils/defs.tex
> Add \ENVVAR and \KEYWORD macros

- content/shmem_test.tex
Fix typo 'evalutes' to 'evaluates' in shmem_test.
> Misspelling in shmem_test

- content/backmatter.tex
Changelog entries for (already merged) #201 and #209 
Closes #217
> Add changelog entries for active set and sym. heap clarifications

- content/backmatter.tex
- content/environment_variables.tex
- utils/packages.tex
> Add support for multipliers in SHMEM_SYMMETRIC_SIZE env var

- content/shmem_init.tex
- content/shmem_reductions.tex
- utils/defs.tex
Clean up some lingering Fortran.  @naveen-rn Could you please review to merge as a DocEdit?
> Update fexample -> cexample

- content/shmem_broadcast.tex
PR #309 rebased onto the current master to resolve merge with other edits.
> [Rebased] Topic/bcast root

- content/shmem_signal_wait_until.tex
This reverts commit 99969f317ddb71d8531dc7e448fb7ddeafdd9902.
Revert #358 
@naveen-rn Please re-post this change as a PR to the relevant section committee.
> Revert "Update full/partial completion to signal_wait_until"

- .github/workflows/main.yml
I am also hoping to use this PR to test the new [openshmem-bot](https://github.com/apps/openshmem-bot).
> Update CI artifact naming

- content/profiling_interface.tex
- content/shmem_pcontrol.tex
- example_code/pshmem_no_weak_symbol.c
- example_code/pshmem_no_weak_symbol_2.c
PR to post section edits for profiling interfaces.
> Section 10: Profiling Interfaces

- content/context_intro.tex
- content/shmem_ctx_create.tex
- content/shmem_ctx_get_team.tex
- content/shmem_reductions.tex
- content/shmem_team_config_t.tex
- content/shmem_team_create_ctx.tex
- content/shmem_team_destroy.tex
- content/shmem_team_get_config.tex
- content/shmem_team_my_pe.tex
- content/shmem_team_n_pes.tex
- content/shmem_team_split_2d.tex
- content/shmem_team_split_strided.tex
- content/shmem_team_translate_pe.tex
- content/teams_intro.tex
- example_code/shmem_reduce_example.c
- example_code/shmem_team_context.c
- example_code/shmem_team_split_2D.c
- main_spec.tex
Please post section edits to jdinan:sec/ctx-teams
> Section 9.4-9.5: Contexts/Teams

- content/backmatter.tex
- content/collective_intro.tex
- content/shmem_alltoall.tex
- content/shmem_alltoalls.tex
- content/shmem_barrier.tex
- content/shmem_barrier_all.tex
- content/shmem_broadcast.tex
- content/shmem_collect.tex
- content/shmem_reductions.tex
- content/shmem_sync.tex
- content/shmem_sync_all.tex
- content/teams_intro.tex
- main_spec.tex
Collectives Section Committee working branch/PR
> Section 9.11, Collectives

- content/shmem_calloc.tex
- content/shmem_malloc.tex
- content/shmem_malloc_hints.tex
- content/threads_intro.tex
All changes for the sections between 9.1 and 9.3 to be reviewed by the section committee, please post PR against this PR.
> Section 9.1-9.3

- content/shmem_team_destroy.tex
> Behavior is undefined if destroying a predef team

- content/shmem_team_config_t.tex
> Fix typo, wording on shmem_team_config_t

- content/backmatter.tex
- content/shmem_ptr.tex
- content/shmem_team_ptr.tex
- main_spec.tex
Addresses issue #319 and adds a team-based variant to `shmem_ptr`
This PR replaces #459.
> Add shmem_team_ptr

- content/backmatter.tex
> Sessions: fix function names in backmatter (_ctx_)
